### ISSUE TITLE
Support cljs and cljc files

### ISSUE THREAD

**Issue by danielcompton** [hilverd/lein-ns-dep-graph#1]
Is this possible?

**Comment by yzernik** [comment]
+1

**Comment by bilus** [comment]
+10

**Comment by danielcompton** [comment]
I tried upgrading this, but got issues with conflicting tools.reader dependencies when running as a plugin. I've opened https://github.com/technomancy/leiningen/pull/2032 as I suspect it might be a tools.reader dec from clj-http that is causing the problem.

**Comment by atroche** [comment]
Anyone looking for a quick fix can use https://clojars.org/atroche/lein-ns-dep-graph/versions/0.2.0-SNAPSHOT:

Just include `[atroche/lein-ns-dep-graph "0.2.0-SNAPSHOT"]` in `:plugins`, and then run `lein ns-dep-graph -platform cljs`.

Be warned that it'll fail on any project (e.g. reagent) that puts tools.namespace 0.2.x on the classpath, because it doesn't support CLJS.
